### ISSUE TITLE
SSL for lab.lepture.com

### ISSUE THREAD

**Issue by manuelmeurer** [lepture/github-cards#26]
Just noticed I cannot use your service since http://lab.lepture.com/ doesn't run on SSL... any chance you can enable SSL at some point in time? :smile:

**Comment by lepture** [comment]
@roalcantara @manuelmeurer I've submitted it to jsdelivr https://github.com/jsdelivr/jsdelivr/pull/3965

**Comment by lepture** [comment]
@manuelmeurer @roalcantara available on jsdelivr: https://cdn.jsdelivr.net/github-cards/latest/widget.js

**Comment by manuelmeurer** [comment]
Awesome, thanks!
