### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by dawsonbotsford** [lepture/github-cards#38]
This is the only viable github card repo on Github and I am having a major issue getting the embedded card to appear.

The embedded card instead shows as a grey puzzle-peace for no clear reason. The console also shows no errors.

---
<br>
<b>Here is what I embedded</b>:
```js
<div class="github-card" data-github="dawsonbotsford" data-width="400" data-height="150" data-theme="default"></div>
<script src="https://cdn.jsdelivr.net/github-cards/latest/widget.js"></script>
```

**Comment by JasperDre** [comment]
I just tried the code you embedded and it works fine.

**Comment by dawsonbotsford** [comment]
I just tried it locally with the same issue. But after you said you did not have this issue, I ran the exact same code from a server with no issues. That means **this is unsupported on static sites** like GitHub pages. Are you able to replicate the same behavior?

**Comment by lepture** [comment]
It works on GitHub pages.

If you open your page with file protocol, it won't work.

**Comment by dawsonbotsford** [comment]
Is there any effort to build out support for file protocol? Or is it because there are network operations, you can only do this when served?

**Comment by lepture** [comment]
@dawsonbotsford It is impossible with XMLHttpRequest.
