### ISSUE TITLE
Failed to open HTTP link

### ISSUE THREAD

**Issue by hzxie** [lepture/github-cards#43]
Please see to this [page](https://lab.lepture.com/github-cards/#hzxie/stumgr|default).

The URL in the project is `http://rjxy.hfut.edu.cn/stumgr`. In the GitHub card, it becomes `https://lab.lepture.com/github-cards/cards/rjxy.hfut.edu.cn/stumgr`. Obviously, there's something wrong with your code.

**Comment by lepture** [comment]
@hzxie GitHub API returns your homepage as `rjxy.hfut.edu.cn/stumgr`. 

![image](https://cloud.githubusercontent.com/assets/290496/21581586/4ee28622-d072-11e6-808b-47bb7c937720.png)

Add `http://` prefix to the webpage section of your repo.
