### ISSUE TITLE
No card appears for user GwhsRobotics3

### ISSUE THREAD

**Issue by gregmarra** [lepture/github-cards#57]
I am unable to get a card to render for GitHub user https://github.com/GwhsRobotics3

The preview tool at http://lab.lepture.com/github-cards/#GwhsRobotics3|default shows a blank space instead of a card. Problem persists in both Chrome and Firefox on my Mac.

![image](https://user-images.githubusercontent.com/57101/38461635-6567f0a2-3a8a-11e8-8f22-008070a1fed3.png)

However, the tool works for my own username:

![image](https://user-images.githubusercontent.com/57101/38461640-8cd70d4e-3a8a-11e8-961c-6a0fe109a6bc.png)

I am unable to display a github card for @GwhsRobotics3

**Comment by andrewda** [comment]
#55 should have fixed this, but I believe there hasn't been a release since the PR was merged.

**Comment by lepture** [comment]
published.

**Comment by gregmarra** [comment]
Thank you!
