### ISSUE TITLE
[Bug]GET https://assets-cdn.github.com/assets/modules/aws/aws-bg-*.jpg 404 (Not Found)

### ISSUE THREAD

**Issue by wsgzao** [lepture/github-cards#58]
![](https://i.loli.net/2018/04/19/5ad83a1fc69b8.jpg)

medium.html?user=wsgzao&identity=ghcard-wsgzao-3&client_id=a11a1bda412d928fb39a&client_secret=92b7cf30bc42c49d589a10372c3f9ff3bb310037:1 GET https://assets-cdn.github.com/assets/modules/aws/aws-bg-80b292690ba587b305c2c038c496ffc8ff08d3bf6be6c1ba64d48bedc09cc36f.jpg 404 (Not Found)

Please fix it if you have time

**Comment by lepture** [comment]
fixed.

**Comment by wsgzao** [comment]
![](https://i.loli.net/2018/04/20/5ad946186f6f1.jpg)

@lepture great, very very very fast, and I really like the new skin, Thank you so much

my blog looks much better, ^_^

https://wsgzao.github.io/
