### ISSUE TITLE
Unable to execute on pages reached via `file:///` protocol

### ISSUE THREAD

**Issue by RmbRT** [lepture/github-cards#59]
The protocol-relative links starting with `//...` only work if one is on a remote web page reached via `http://` or `https://`. On local pages, this resolves to `file://...` and the `iframe` cannot be displayed.

**Comment by Starkiller4011** [comment]
Same issue, works fine so long as the loaded page is not reached via `file://...`, even works in code pens such as the W3Schools "Tryit" Editor

**Comment by lepture** [comment]
Limited by browsers: https://github.com/lepture/github-cards/blob/master/src/card.js#L74

**Comment by RmbRT** [comment]
https://github.com/lepture/github-cards/blob/master/src/widget.js#L2 Here, if you'd just check whether the page is located in file://, and for that protocol, prefix the url with https://, then it'd probably work.

**Comment by lepture** [comment]
You can submit a PR to fix it.
