### ISSUE TITLE
Couldn't find the requested release version 1.0.4.

### ISSUE THREAD

**Issue by GuangTianLi** [lepture/github-cards#60]
https://cdn.jsdelivr.net/github-cards/1.0.4/

**Comment by MartinKolarik** [comment]
The link is https://cdn.jsdelivr.net/gh/lepture/github-cards@1.0.4/

**Comment by lepture** [comment]
released 1.0.5

**Comment by GuangTianLi** [comment]
There is still an error, when I use 1.0.5:
`<div class="github-card" data-user="lepture" data-repo="github-cards"></div>`
`<script src="https://cdn.jsdelivr.net/gh/lepture/github-cards@1.0.5/jsdelivr/widget.js"></script>`

Error:
`Couldn't find the requested file /cards/default.html in lepture/github-cards.`
