### ISSUE TITLE
User / repo is not found

### ISSUE THREAD

**Issue by sebastianbochan** [lepture/github-cards#68]
I came across a simple issue (I guess). When I type username or repo it always returns error  (also in your cards generator).

URL:
- https://lab.lepture.com/github-cards/#https://github.com/lepture|default
- https://lab.lepture.com/github-cards/#https://github.com/lepture/github-cards|default

**Comment by lepture** [comment]
https://lab.lepture.com/github-cards/#lepture|default

https://lab.lepture.com/github-cards/#lepture/github-cards|default
